account for missing files and directories

diff --git a/lib/clickfunc b/lib/clickfunc
--- a/lib/clickfunc
+++ b/lib/clickfunc
@@ -3,6 +3,7 @@ function build_click () {
     if ! check_cmd click; then err "missing click"; fi
     cd ${ROOT};
     [ ! -f "manifest.json" &&  ! -f "manifest.json.in"  ] && err "missing manifest.json";
+    [ ! -f "apparmor.json" ] && err "missing apparmor.json";
     [ -d "${BUILD_DIR}" ] && rm -r ${BUILD_DIR}
     [ -d "${APTSTATE}/lists" ] || {
         say "Fetching package lists...";
@@ -32,10 +33,19 @@ function build_click () {
 function prep_build () {
 	[ -d "${INSTALL_DIR}" ] && rm -r ${INSTALL_DIR}
 	mkdir -p ${CLICK_LD_LIBRARY_PATH} ${CLICK_PATH} ${INSTALL_DIR}
-	cp ${ROOT}/pkg.desktop ${BUILD_DIR}/${PKG}.desktop
-	cp ${ROOT}/pkg.d/* ${ROOT}/apparmor.json ${ROOT}/manifest.json ${BUILD_DIR}/ || exit 1
-	sed -i "s/@pkg@/${PKG}/" ${BUILD_DIR}/manifest.json
+	check_file ${ROOT}/pkg.desktop ${BUILD_DIR}/${PKG}.desktop
+	check_file ${ROOT}/manifest.json
+	[[ -d "${ROOT}/pkg.d" ]] && cp ${ROOT}/pkg.d/* ${BUILD_DIR}/
+	cp ${ROOT}/apparmor.json ${BUILD_DIR}/ || exit 1
+	if [[ -f "${ROOT}/manifest.json" ]]; then
+		sed -i "s/@pkg@/${PKG}/" ${BUILD_DIR}/manifest.json
+	fi
 	sed -i "s/@pkg@/${PKG}/" ${BUILD_DIR}/${PKG}.desktop
 	cp ${BUILD_DIR}/${PKG}.desktop ${BUILD_DIR}/*.json ${INSTALL_DIR}
 	cp ${BUILD_DIR}/pkg.sh ${CLICK_PATH}/${PKG}.sh
+}
+
+function check_file () {
+	$file=$1;
+	[[ -f "$file" ]] && cp $file ${2:${BUILD_DIR}}/
 }
